### ISSUE TITLE
Specifying an alternative root directory

### ISSUE THREAD

**Issue by pigmonkey** [carnager/rofi-pass#9]
I have an alternative pass store at `~/otherpass`. I'm trying to use rofi-pass to interact with that store.

    $ rofi-pass --root ~/otherpass

This results in a rofi window with no password entries.

It looks like on line 38 rofi-pass is trying to append the root dir to the default password store, resulting in something like `/home/user/.password-store///home/user/otherpass`. I think the line should be something more like:

         	passwords=( "${root}"/**/*.gpg )

Line 44 will also need to be altered so that the pass store dir is stripped from the filenames.

**Comment by carnager** [comment]
right now specifying a root dir is indeed meant as a subdir of $basedir (set in config)
I agree making it totally independent might be the better idea. 
will work on that

**Comment by pigmonkey** [comment]
I see. I misunderstood the intent of the root flag.

I have two completely separate password stores -- one for work, one for personal use. Being able to pass in the directory of the work password store would allow me to use rofi-pass for work. I would still leave my personal store defined as the basedir in the config, since that's what I would want rofi-pass to default to.

**Comment by carnager** [comment]
can you try latest git?

**Comment by pigmonkey** [comment]
With root defined in password store it works fine, but it also echoes all file names to the terminal, which is kind of annoying. It also prints whatever action it takes. For instance, if I simply execute rofi-pass and then hit escape, it prints:

````
+ selected_password=
+ rofi_exit=1
+ [[ -n '' ]]
+ [[ 1 -eq 13 ]]
+ [[ 1 -eq 1 ]]
+ exit 1
````

With no root defined in the config, it does the same thing, except it now no longer strips the path from each file. So I see `/home/user/.password-store/...` for each file.

Executing `rofi-pass --root /home/user/otherpass` does result in rofi-pass using the alternative pass store, but it also prints all the files to the terminal.

**Comment by pigmonkey** [comment]
I think the printing is just due to the `bash -x`.

**Comment by carnager** [comment]
It is, forgot to remove it. Can't push right now, since my Internet broke down. Will fix later. 

You might want to consider setting a hotkey for rofi 

You can use something like this:
```menu=$(echo -e "$HOME/test-store\n/path/to/other-root" | rofi -dmenu); rofi-pass --root "${menu}"
```

**Comment by pigmonkey** [comment]
I found another problem with this commit now that I've actually tried to copy usernames/passwords.

With root defined in the config, it works fine.

With root undefined, pass throws an error, probably because rofi-pass isn't stripping the default path from the filenames:

    Error: /home/user/.password-store/web/google is not in the password store.

When using `--root ~/otherpass` it also throws an error, perhaps because rofi-pass leaves a `/` in front of the file name. For instance, if I want to copy the username from `/home/user/otherpass/github`:

    Error: /github is not in the password store.

(Using `rofi -dmenu` to choose the pass store is a good idea. Thanks!)

**Comment by carnager** [comment]
The leading slash is no issue. It simply needs a check for empty variable. Again, when Internet works again ;)

**Comment by carnager** [comment]
i can't reproduce it. disabled root= in config. works fine

**Comment by carnager** [comment]
fixed for all actions in main menu. other menus follow

**Comment by pigmonkey** [comment]
Works with no root specified in config or command line. Works with root specified in config. Works with root specified on command line. Great!

`bash -x` is still outputting everything.

`--last-used` does not work when I specify an alternative root directory. Perhaps the last used file should contain one key value pair per password store per line, like

```
/home/user/.password-store: web/google
/home/user/otherpass: github
```

When `--last-used` is used, rofi-pass could check if that file exists and, if it does, grep through it for whatever the current `root` is. If a line matches, use sed or awk to split at the `:` and use the second part as the last used entry.

To update the last-used password, I guess you would also have to grep for the current root to see if an entry already exists. Grep can return the matching line number and then sed or awk can replace that specific line number.

That definitely increases the complexity of the last used logic, but that flag is super useful. I use it all the time when I want to copy the username and password rather than autotype both.

Thanks for all the work!

**Comment by carnager** [comment]
oh good catch. i will look into it

**Comment by Narrat** [comment]
Shouldn't be checked when assigning ROOT if PASSWORD_STORE_DIR exists as environment var?
I use just one password store dir, but not at the default location and therefor set the var.
So I would need to use --root option regardless, as it just assigns the default dir.

So imo I would assume something like:
1.) Check on --root option
2.) No? Check on env var PASSWORD_STORE_DIR
3.) Still not? Set default

**Comment by carnager** [comment]
it is using PASSWORD_STORE_DIR

**Comment by Narrat** [comment]
Yeah. But if PASSWORD_STORE_DIR is set in the .bashrc/.zshrc/etc it won't be taken into account.
In every case this var will be written by rofi-pass regardless if existing or not

**Comment by carnager** [comment]
I tested around with this and for some reason globally exported variable was never accepted. I will have another look later

**Comment by carnager** [comment]
ok, it's done like this now:

* check for --last-used parameter. if present use root from this
* check for --root parameter and use it
* check for root config option
* check for PASSWORD_STORE_DIR env var
* if nothing applies, use default

**Comment by pigmonkey** [comment]
This works:

    $ rofi-pass --last-used --root ~/otherpass

This fails:

    $ rofi-pass --root ~/otherpass --last-used

**Comment by pigmonkey** [comment]
> check for --last-used parameter. if present use root from this

I'm conflicted about this. On one hand I can see how it would be useful to always open the last used root, on the other hand I kind of want it to always default to my normal password store (whether it gets that through the env var, config file, or its own fallback) unless I explicitly tell it otherwise.

**Comment by carnager** [comment]
if the last used entry was from a different root, it was from a different root. why would the last used entry suddenly be elsewhere? :)

**Comment by pigmonkey** [comment]
Yeah, good point. It does makes sense given the way `--last-used` currently works.

**Comment by carnager** [comment]
regarding order of arguments: I consider this obsolete for now, because of the way --last-used is intended to work.

I might implement multi-root support for --last-used/--show-last at a later point and close this for now
